version: '2'
services:
    airmate-app:
        image: airmate
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://airmate-mysql:3306/airmate?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8085:8085
    airmate-mysql:
        extends:
            file: mysql.yml
            service: airmate-mysql
